language: c
sudo: required
services:
    - docker

env:
    global:
        - LD_LIBRARY_PATH=/usr/local/lib

addons:
    apt:
        config:
            retries: true
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
        packages:
            - cmake
            - gcc-7
            - lcov
            - clang-6.0
            - valgrind
            - libev-dev
            - libc-ares-dev
            - g++-7
            - libstdc++-7-dev
            - stunnel4
            - libidn2-0-dev
            - libssh2-1-dev
            - libssh-dev
            - krb5-user
            - autopoint  # for libpsl that needs autoreconf that uses gettext that needs it
            - libunistring-dev # for libidn2 neeed by libpsl

matrix:
    include:
        - os: linux
          compiler: gcc
          dist: trusty
          env: T=normal
        - os: linux
          compiler: gcc
          dist: trusty
          env: T=dockertest

script:
    - |
        set -eo pipefail
        if [ "$T" = "normal" ]; then
             ./normal.sh
        fi
    - |
        set -eo pipefail
        if [ "$T" = "dockertest" ]; then
            docker run -i -v $PWD:/codebase -w /codebase cmeister2/fuzzer-build ./normal.sh
        fi


# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
    only:
        - master

notifications:
  email: false
